In [2]:
import numpy as np

In [22]:
a = np.array([(1,3,5,7,9,11),(2,3,4,5,6,7)])
print(a)

a = np.arange(1, 12, 2)    # (start, stop, step)
print(a)

a = np.linspace(5, 8, 13)  # (start, stop, number of items)
print(a)

a = np.zeros((4, 2))
print(a)

a = np.ones((2, 3), dtype=np.int16)
print(a)

a = np.full((6,), 88)
print(a)

a = np.fromstring('25 30 35 40', dtype=int, sep=' ')
print(a)

a = np.array([[1,3,5],[7,9,11]])
print(a)

b = np.zeros_like(a)    # _like gives you a new array in the same shape as the argument.
print(b)

[[ 1  3  5  7  9 11]
 [ 2  3  4  5  6  7]]
[ 1  3  5  7  9 11]
[5.   5.25 5.5  5.75 6.   6.25 6.5  6.75 7.   7.25 7.5  7.75 8.  ]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[1 1 1]
 [1 1 1]]
[88 88 88 88 88 88]
[25 30 35 40]
[[ 1  3  5]
 [ 7  9 11]]
[[0 0 0]
 [0 0 0]]


In [5]:
print(a.size)
print(a.shape)
print(a.ndim)
print(a.itemsize)
print(a.dtype)
print(a.nbytes)  # same as a.size * a.itemsize

6
(2, 3)
2
4
int32
24


In [6]:
print(a)
print(a[1])
print(a[0][2])
print(b[2:4])

print(a[:1])
print(a[1:3:2])
print(a[:, 1:2])  # all elements on dimension 0, only element 1 on dimension 1

[[ 1  3  5]
 [ 7  9 11]]
[ 7  9 11]
5
[]
[[1 3 5]]
[[ 7  9 11]]
[[3]
 [9]]


In [11]:
c = np.arange(-9, -3).reshape(2,3)
print(c)

c = c.swapaxes(0,1)
print(c)

c = c.flatten()
print(c)

[[-9 -8 -7]
 [-6 -5 -4]]
[[-9 -6]
 [-8 -5]
 [-7 -4]]
[-9 -6 -8 -5 -7 -4]


In [8]:
d = np.arange(0,100)
print(d.dtype, type(d[1]))
print(d.nbytes)

d = np.arange(0,100, dtype='int8')
print(d.dtype, type(d[1]))
print(d.nbytes)

int32 <class 'numpy.int32'>
400
int8 <class 'numpy.int8'>
100


In [18]:
e = np.array([(1.566666,2,3), (4,5,6)])
print(e.dtype)

e = e.round(4)
print(e)

np.set_printoptions(precision=2, suppress=True)    # show 2 decimal places, suppress scientific notation
print(e)

float64
[[1.57 2.   3.  ]
 [4.   5.   6.  ]]
[[1.57 2.   3.  ]
 [4.   5.   6.  ]]


In [10]:
np.set_printoptions(precision=5, suppress=True)    # show 5 decimal places, suppress scientific notation
h = np.random.random(6)
print(h)

h = np.random.randint(10, 99, 8)    # (low, high inclusive, size)
print(h)

np.random.shuffle(h)        # in-place shuffle
print(h)

print(np.random.choice(h))

h.sort()                    # in-place sort
print(h)

[0.16328 0.31574 0.95609 0.80999 0.70806 0.15606]
[55 72 72 11 48 98 81 55]
[81 72 72 48 98 55 11 55]
55
[11 48 55 55 72 72 81 98]
